### PR TITLE
Wait with additional requests until table is interacted with

### PR DESCRIPTION
**Pull request by heralden**
Only the first tablerows request is necessary to display the content of the im-table. The remaining requests only populate data that will *probably* be used later on during interaction. By saving them for later, we will reduce the amount of initial HTTP requests from 3+ to only 1.

On the [Bluegenes report page for eve](http://localhost:5000/default/report/Gene/1007318) this gives the following performance difference on a cold start (full refresh) in prod mode:

**Before change**
1065 HTTP requests
19.19 seconds

**After change**
88 HTTP requests
6.27 seconds

This PR should be tested by comparing the network panel output in your browser's dev tools, and by testing that none of the functionality of im-tables-3 has degraded.

### CODE REVIEW

**Review by yochannah — APPROVED** [review]
Tested the feature and it works nicely. One comment - it is a little hard to review a change when there are also a lot of unrelated whitespace formattings / refactors as well, even with the ignore whitespace switch. It might be easier to make two or more separate PRs next time, just so the reviewer can tell whether there's actually a real change or just some brackets moved :)

**Comment by yochannah** [comment]
Oh, I wanted to add that all the readme stuff _is_ really good - nice one! :)

**Comment by heralden** [comment]
I agree, a separate PR would have been more optimal.

But note that you can open the commit directly (https://github.com/intermine/im-tables-3/pull/59/commits/075b9a0d9263c13aa66c6c88fa0617abf97f0bf5) as the *superficial* stuff is done in separate commits.

**Comment by yochannah** [comment]
I wondered if you'd raise that point lol :)

**Pull request merged**
