### PR TITLE
Summary fields for popovers

### PR DESCRIPTION
**Pull request by yochannah**
popovers for cells were returning *all* attributes of a class, not just the summary fields. This made things ridiculously long for classes with many attributes, like proteins from yeastmine with 40+ properties.

### CODE REVIEW

**Comment by yochannah** [comment]
@uosl this is a really old PR but still relevant - I didn't have anyone who could review it at the time when I made the PR :laughing:

**Comment by heralden** [comment]
Here's the real diff for future reference:
```diff
diff --git a/src/im_tables/events.cljs b/src/im_tables/events.cljs
index 643b075..ede9a6d 100644
--- a/src/im_tables/events.cljs
+++ b/src/im_tables/events.cljs
@@ -523,17 +518,15 @@
  (fn [{db :db} [_ loc {:keys [class id] :as item}]]
    (cond-> {:db db}
      (not (get-in db [:cache :item-details id]))
-     (assoc :im-tables/im-operation {:on-success
-                                     [:main/cache-item-summary loc]
-                                     :op
-                                     (partial fetch/records
-                                              (get db :service)
-                                              (summary-query
-                                               (assoc item :summary-fields
-                                                      (into [] (keys (get-in db [:service :model :classes (keyword class) :attributes]))))))}))))
-
-
-
+     (assoc :im-tables/im-operation
+            {:on-success
+             [:main/cache-item-summary loc]
+             :op
+             (partial fetch/records
+                      (get db :service)
+                      (summary-query
+                       (assoc item :summary-fields
+                              (into []  (get-in db [:service :summary-fields (keyword class)])))))}))))
 
 ;;;;;;;;;;;;;;
 
diff --git a/src/im_tables/views.cljs b/src/im_tables/views.cljs
index e35992c..e792cf3 100644
--- a/src/im_tables/views.cljs
+++ b/src/im_tables/views.cljs
@@ -5,14 +5,11 @@
             [reagent.dom.server :as server]
             [oops.core :refer [ocall]]))
 
-(def some-im-tables-config {:service {:root "beta.humanmine.org/beta"}
-                            :query {:from "Gene"
+(def some-im-tables-config {:service {:root "https://yeastmine.yeastgenome.org/yeastmine"}
+                            :query {:from "Protein"
                                     :select ["symbol"
                                              "secondaryIdentifier"
-                                             "dataSets.description"
-                                             "primaryIdentifier"
-                                             "organism.name"
-                                             "dataSets.name"]}
+                                             "primaryIdentifier"]}
                             :settings {:pagination {:limit 10}
                                        :links {:vocab {:mine "BananaMine"}
                                                :url (fn [vocab] (str "#/reportpage/"
```

**Review by heralden — APPROVED** [review]

**Comment by heralden** [comment]
Compared popovers before and after change, and the difference is from a 30 line popover to a more manageable 4 line one, for the Yeastmine data.

**Pull request merged**
